### ISSUE TITLE
Still under development

### ISSUE THREAD

**Issue by wbuchanan** [robertgrant/stata2d3#1]
Hey Robert,

Been a while since we last spoke and wanted to drop you a line to see if you were still developing this?  I just started working on a JSON serializer for Stata (github.com/wbuchanan/StataJSON) with the ultimate end goal being a plugin that could use something analogous to ggplot2 style syntax to build D3 graphics via the Java API (e.g., build out persistence objects that would allow the end user to assemble the D3 components in a way that might be a bit more intuitive for them).  Haven't experimented with what would happen if a GUI based Java application was called from the Java API, but thought it might be interesting if the plugin launched a "browser" via a Java Swing/FX window.  

Also, I ended up building out a program to generate customized scheme files for Stata that make color palettes from Color Brewer and a few other research based resources available to mix and match based on graph types (github.com/wbuchanan/brewscheme).

**Comment by wbuchanan** [comment]
Planning on updates for [brewscheme](http://wbuchanan.github.io/brewscheme/) to generate similarly formatted CSS.  Also, just started building out Mata interfaces for generating HTML and D3 code.  If you wanted to pool our efforts to make it easier to generate D3 based graphs in Stata let me know.

**Comment by wbuchanan** [comment]
Just a quick update in case you were interested.  The D3 Mata wrapper is working and I started a simple example [submodule](https://wbuchanan.github.io/d3mata-examples) to show how it can be used to create Mata functions that write out the [JavaScript](http://wbuchanan.github.io/d3mata) and [HTML](http://wbuchanan.github.io/matahtml) needed for a visualization.

**Comment by robertgrant** [comment]
@tpmorris and I are doing a presentation of a simple new version of this at London conf which will work on SVG outputs from Stata. We don't intend to make it all-encompassing, just to give Stata users who are JS-naive a starting point for hacking the resulting html+svg+js file. It seems your efforts have been more comprehensive and I don't see this repo as overlapping much with yours, so I'll close this issue but will of course be interested in any ideas you have (PS right now, it is work in progress but take a look by end September)
