### ISSUE TITLE
options for linking to d3.js

### ISSUE THREAD

**Issue by robertgrant** [robertgrant/stata2d3#3]
For @tpmorris to consider in syntax. We need options in -d3- that create one of:

- a link to a local d3.v*.min.js
- a link to the remote muthaship http://d3js.org/d3.v*.min.js

A local link saves any issues with browser security settings, plus works even if you're offline. But maybe the remote link should be the default? So the option could be LOcald3

Note I'm only working with d3 v3 at present.

**Comment by tpmorris** [comment]
Done in d3.ado. The default is remote muthaship v3 but users can specify a local library or alternative remote version.
